frr version 8.4_git
frr defaults traditional
hostname b7c1f79fc13e
no ipv6 forwarding
!
interface dummy0
 description Dummy — OSPF transit network simulation
 ip address 10.0.0.1/24
 no ip ospf passive
exit
!
interface dummy1
 description Dummy — Customer network simulation
 ip address 192.168.1.1/24
exit
!
interface dummy2
 description Dummy — Additional network for BGP advertisement
 ip address 172.16.0.1/24
exit
!
interface lo
 description Loopback — Router-ID source
 ip address 1.1.1.1/32
exit
!
router bgp 65000
 bgp router-id 1.1.1.1
 bgp log-neighbor-changes
 neighbor 10.0.0.2 remote-as 65000
 neighbor 10.0.0.2 description Example-iBGP-Peer
 neighbor 10.0.0.2 update-source lo
 neighbor 10.0.0.2 timers 10 30
 !
 address-family ipv4 unicast
  network 1.1.1.1/32
  network 10.0.0.0/24
  network 172.16.0.0/24
  network 192.168.1.0/24
  neighbor 10.0.0.2 next-hop-self
 exit-address-family
exit
!
router ospf
 ospf router-id 1.1.1.1
 passive-interface default
 network 1.1.1.1/32 area 0.0.0.0
 network 10.0.0.0/24 area 0.0.0.0
 network 172.16.0.0/24 area 0.0.0.0
 network 192.168.1.0/24 area 0.0.0.0
exit
!
line vty
 no login
exit
!
rpki
exit
!
