#!/usr/bin/env python3
"""
NetCert — JNCIP-ENT (JN0-649) question generator.
Aligned with Juniper Enterprise Routing and Switching Professional objectives.
"""
import hashlib
import json
import uuid

EXAM_ID = "b0000000-0000-0000-0000-000000000011"
TRACK_ID = "a0000000-0000-0000-0000-000000000001"


def qid(seed: str) -> str:
    return str(uuid.uuid5(uuid.NAMESPACE_OID, f"jncip-ent:{seed}"))


def content_hash(body: str, correct: str) -> str:
    return hashlib.sha256(f"{body}::{correct}".encode()).hexdigest()[:16]


def make_q(body: str, options: list[tuple[str, bool]], explanation: str,
           section: str, weight: float, difficulty: int = 3,
           bloom: str = "understand", urls: list[str] | None = None) -> dict:
    assert sum(1 for _, c in options if c) == 1, f"exactly one correct option required: {body}"
    letters = "ABCDEF"
    opts = []
    for i, (text, correct) in enumerate(options):
        opts.append({"id": letters[i], "text": text, "is_correct": correct})
    correct_letter = next(letters[i] for i, (_, c) in enumerate(options) if c)
    return {
        "id": qid(body + correct_letter),
        "exam_id": EXAM_ID,
        "track_id": TRACK_ID,
        "question_type": "single-choice",
        "difficulty": difficulty,
        "bloom_level": bloom,
        "body": body,
        "options": opts,
        "explanation": explanation,
        "reference_urls": urls or ["https://www.juniper.net/us/en/training/certification/certification-tracks/jncip-ent.html"],
        "blueprint_section": section,
        "blueprint_weight": weight,
        "content_hash": content_hash(body, correct_letter),
        "is_active": True,
    }


def generate_questions() -> list[dict]:
    questions = [
        # Layer 2 / Switching
        make_q("Which spanning-tree protocol is the IEEE standard that converges faster than STP?",
               [("STP", False), ("RSTP", True), ("PVST+", False), ("MSTP", False)],
               "RSTP (802.1w) is the IEEE standard that provides faster convergence than legacy STP (802.1D).",
               "Layer 2 Switching", 12.0, 2, "remember"),
        make_q("Which feature should be enabled on switch access ports to immediately transition them to forwarding?",
               [("BPDU Guard", False), ("Root Guard", False), ("PortFast", True), ("Loop Guard", False)],
               "PortFast allows access ports to skip listening and learning states and go directly to forwarding.",
               "Layer 2 Switching", 12.0, 2, "apply"),
        make_q("Which protocol provides loop-free Layer 2 topology in a multi-vendor environment?",
               [("VTP", False), ("DTP", False), ("RSTP", True), ("PAgP", False)],
               "RSTP/MSTP are IEEE standards for loop-free Layer 2. VTP manages VLANs, DTP negotiates trunks, PAgP is Cisco-proprietary.",
               "Layer 2 Switching", 12.0, 2, "understand"),
        make_q("Which Junos command configures an aggregated Ethernet interface with LACP?",
               [("set interfaces ae0 aggregated-ethernet lacp active", True),
                ("set interfaces ae0 ether-options 802.3ad", False),
                ("set interfaces ge-0/0/0 channel-group 1", False),
                ("set interfaces ae0 lacp enable", False)],
               "In Junos, LACP is enabled on aggregated Ethernet interfaces with 'aggregated-ethernet-options lacp active'.",
               "Layer 2 Switching", 12.0, 2, "apply"),
        make_q("Which VLAN tagging protocol is an IEEE standard?",
               [("ISL", False), ("DTP", False), ("802.1Q", True), ("VTP", False)],
               "802.1Q is the IEEE standard for VLAN tagging. ISL is Cisco-proprietary and deprecated.",
               "Layer 2 Switching", 12.0, 1, "remember"),
        make_q("What is the purpose of BPDU Guard?",
               [("To prevent root bridge changes", False),
                ("To disable PortFast ports that receive BPDUs", True),
                ("To block inferior BPDUs", False), ("To enable rapid convergence", False)],
               "BPDU Guard protects PortFast ports by putting them in err-disabled state if they receive a BPDU.",
               "Layer 2 Switching", 12.0, 2, "understand"),
        make_q("Which Junos command shows the Ethernet switching table?",
               [("show ethernet-switching table", True), ("show mac-address-table", False),
                ("show bridge table", False), ("show switching-table", False)],
               "Junos uses 'show ethernet-switching table' to display MAC address learning on switching platforms.",
               "Layer 2 Switching", 12.0, 1, "apply"),

        # OSPF / IS-IS
        make_q("Which OSPF area type can contain routes from multiple areas but does not originate external routes?",
               [("Standard area", False), ("Stub area", False), ("Totally stubby area", False), ("Backbone area", True)],
               "Area 0 is the OSPF backbone. It connects all other areas and can contain inter-area and external routes.",
               "OSPF", 12.0, 2, "understand"),
        make_q("Which IS-IS level forms the backbone?",
               [("Level 1", False), ("Level 2", True), ("Level 1/2", False), ("Level 0", False)],
               "IS-IS Level 2 routers form the backbone and know the full inter-area topology.",
               "IS-IS", 12.0, 2, "remember"),
        make_q("Which OSPF LSA type is generated by an ABR to advertise inter-area routes?",
               [("Type 1", False), ("Type 2", False), ("Type 3", True), ("Type 5", False)],
               "Type 3 LSAs (summary LSAs) are originated by ABRs to advertise inter-area routes.",
               "OSPF", 12.0, 2, "remember"),
        make_q("Which command displays IS-IS adjacencies on a Junos device?",
               [("show isis neighbors", False), ("show isis adjacency", True),
                ("show isis interface", False), ("show isis database", False)],
               "'show isis adjacency' displays IS-IS neighbor adjacencies and their states.",
               "IS-IS", 12.0, 1, "apply"),
        make_q("Which OSPF network type elects a DR/BDR?",
               [("Point-to-point", False), ("Broadcast", True), ("Point-to-multipoint", False), ("Loopback", False)],
               "Broadcast and NBMA OSPF network types elect a DR/BDR to reduce adjacency count.",
               "OSPF", 12.0, 1, "remember"),

        # BGP
        make_q("Which BGP attribute is preferred when higher?",
               [("MED", False), ("AS Path length", False), ("Local Preference", True), ("Router ID", False)],
               "Local Preference is preferred when higher. MED is preferred when lower, and shorter AS Path is preferred.",
               "BGP", 12.0, 2, "understand"),
        make_q("Which BGP feature allows a router to advertise multiple paths for the same prefix?",
               [("Add-path", True), ("Multipath", False), ("Route reflector", False), ("Confederation", False)],
               "BGP add-path allows a router to advertise multiple paths for the same prefix to a peer.",
               "BGP", 12.0, 2, "understand"),
        make_q("Which Junos policy action sets the BGP local preference?",
               [("set local-preference 200", True), ("set preference 200", False),
                ("set metric 200", False), ("set as-path-prepend 200", False)],
               "In Junos, 'set local-preference <value>' sets the BGP LOCAL_PREF attribute.",
               "BGP", 12.0, 2, "apply"),
        make_q("What is the purpose of BGP confederations?",
               [("To encrypt BGP sessions", False),
                ("To divide a large AS into smaller sub-ASes to reduce iBGP mesh", True),
                ("To replace route reflectors", False), ("To aggregate routes", False)],
               "BGP confederations split a large autonomous system into smaller sub-ASes, reducing the full-mesh iBGP requirement.",
               "BGP", 12.0, 2, "understand"),

        # Multicast
        make_q("Which PIM mode uses source trees only and does not require a rendezvous point?",
               [("PIM-SM", False), ("PIM-DM", False), ("PIM-SSM", True), ("Bidir-PIM", False)],
               "PIM Source-Specific Mode (SSM) uses source trees only and does not require a rendezvous point.",
               "Multicast", 8.0, 2, "understand"),
        make_q("Which IGMP version supports source-specific queries?",
               [("IGMPv1", False), ("IGMPv2", False), ("IGMPv3", True), ("IGMPv4", False)],
               "IGMPv3 supports source-specific multicast (SSM) and source filtering.",
               "Multicast", 8.0, 2, "remember"),

        # CoS / EVPN
        make_q("Which Junos CoS component rewrites outgoing DSCP or IEEE 802.1p bits?",
               [("Classifier", False), ("Rewrite rule", True), ("Scheduler", False), ("Drop profile", False)],
               "Rewrite rules modify outgoing packet markings such as DSCP or 802.1p.",
               "CoS", 8.0, 2, "understand"),
        make_q("Which EVPN route type is used for inclusive multicast Ethernet tag route?",
               [("Type 1", False), ("Type 2", False), ("Type 3", True), ("Type 4", False)],
               "EVPN Type 3 routes are inclusive multicast routes used for broadcast, unknown unicast, and multicast flooding.",
               "EVPN", 8.0, 2, "remember"),
        make_q("Which EVPN route type advertises Ethernet segment information for Designated Forwarder election?",
               [("Type 1", False), ("Type 2", False), ("Type 3", False), ("Type 4", True)],
               "EVPN Type 4 routes advertise Ethernet segment information and are used for Designated Forwarder election.",
               "EVPN", 8.0, 2, "remember"),
        make_q("Which CoS feature shapes traffic by buffering excess instead of dropping it?",
               [("Policer", False), ("Shaper", True), ("Scheduler", False), ("Classifier", False)],
               "Shapers buffer and smooth traffic to conform to a rate. Policers drop or remark excess traffic.",
               "CoS", 8.0, 2, "understand"),

        # Extended Layer 2 / Switching
        make_q("Which spanning-tree mode allows multiple VLANs to share a single spanning-tree instance?",
               [("PVST+", False), ("RSTP", False), ("MSTP", True), ("STP", False)],
               "MSTP (802.1s) maps multiple VLANs to multiple spanning-tree instances, reducing overhead compared to per-VLAN RSTP.",
               "Layer 2 Switching", 12.0, 2, "understand"),
        make_q("Which command configures an access interface in VLAN 100 on a Junos EX switch?",
               [("set interfaces ge-0/0/0 unit 0 family ethernet-switching vlan members 100", True),
                ("set interfaces ge-0/0/0 switchport access vlan 100", False),
                ("set vlan 100 interface ge-0/0/0", False), ("set interfaces ge-0/0/0 vlan 100", False)],
               "On Junos EX, access VLAN membership is configured under 'family ethernet-switching vlan members'.",
               "Layer 2 Switching", 12.0, 2, "apply"),
        make_q("Which feature protects against accidental BPDUs on PortFast-like edge ports in Junos?",
               [("BPDU Guard", True), ("Root Guard", False), ("Loop Guard", False), ("BPDU Filter", False)],
               "BPDU Guard disables edge ports that receive BPDUs, preventing accidental switch connections.",
               "Layer 2 Switching", 12.0, 2, "understand"),
        make_q("Which protocol negotiates an aggregated Ethernet link between switches?",
               [("VRRP", False), ("LACP", True), ("RSTP", False), ("DTP", False)],
               "LACP (Link Aggregation Control Protocol, 802.3ad) dynamically negotiates aggregated Ethernet links.",
               "Layer 2 Switching", 12.0, 1, "remember"),
        make_q("Which Junos command shows the MAC learning table on an EX switch?",
               [("show ethernet-switching table", True), ("show mac-address-table", False),
                ("show bridge table", False), ("show switching-table", False)],
               "'show ethernet-switching table' displays learned MAC addresses on Junos EX switches.",
               "Layer 2 Switching", 12.0, 1, "apply"),
        make_q("Which feature provides default gateway redundancy using a virtual IP?",
               [("LACP", False), ("VRRP", True), ("RSTP", False), ("LLDP", False)],
               "VRRP provides default gateway redundancy by sharing a virtual IP between routers.",
               "Layer 2 Switching", 12.0, 2, "understand"),
        make_q("Which STP guard prevents a port from becoming the root port?",
               [("BPDU Guard", False), ("Root Guard", True), ("Loop Guard", False), ("Storm Control", False)],
               "Root Guard prevents a port from accepting superior BPDUs and becoming a root port.",
               "Layer 2 Switching", 12.0, 2, "understand"),
        make_q("Which protocol advertises device identity and capabilities between directly connected neighbors?",
               [("CDP", False), ("LLDP", True), ("VTP", False), ("DTP", False)],
               "LLDP (Link Layer Discovery Protocol) is an IEEE standard for neighbor discovery. CDP is Cisco-proprietary.",
               "Layer 2 Switching", 12.0, 1, "remember"),
        make_q("Which command configures a trunk interface carrying VLANs 10-20 on Junos EX?",
               [("set interfaces ge-0/0/0 unit 0 family ethernet-switching interface-mode trunk vlan members 10-20", True),
                ("set interfaces ge-0/0/0 switchport mode trunk allowed-vlan 10-20", False),
                ("set interfaces ge-0/0/0 trunk vlan 10-20", False), ("set vlan trunk 10-20 interface ge-0/0/0", False)],
               "Junos EX trunk configuration uses 'interface-mode trunk' and 'vlan members' under ethernet-switching.",
               "Layer 2 Switching", 12.0, 2, "apply"),
        make_q("Which spanning-tree state in RSTP discards frames but listens for BPDUs?",
               [("Discarding", True), ("Blocking", False), ("Listening", False), ("Learning", False)],
               "RSTP uses Discarding state, which combines legacy Blocking and Listening states.",
               "Layer 2 Switching", 12.0, 2, "remember"),

        # Extended OSPF / IS-IS
        make_q("Which OSPF LSA type describes routes to ASBRs?",
               [("Type 1", False), ("Type 2", False), ("Type 3", False), ("Type 4", True)],
               "Type 4 Summary ASBR-LSAs describe the location of ASBRs to other areas.",
               "OSPF", 12.0, 3, "remember"),
        make_q("Which OSPF network type requires manual neighbor configuration?",
               [("Broadcast", False), ("Point-to-point", False), ("NBMA", True), ("Multi-access", False)],
               "Non-Broadcast Multi-Access (NBMA) OSPF network types require manual neighbor statements.",
               "OSPF", 12.0, 2, "remember"),
        make_q("Which command enables IS-IS on an interface in Junos?",
               [("set protocols isis interface ge-0/0/0", True), ("set isis interface ge-0/0/0", False),
                ("set protocols isis enable ge-0/0/0", False), ("set interface ge-0/0/0 isis", False)],
               "'set protocols isis interface <name>' enables IS-IS on the specified interface.",
               "IS-IS", 12.0, 1, "apply"),
        make_q("Which OSPF area accepts external routes as Type 7 LSAs?",
               [("Stub", False), ("Totally stubby", False), ("NSSA", True), ("Standard", False)],
               "NSSA areas allow external routes to be advertised as Type 7 LSAs, converted to Type 5 at the ABR.",
               "OSPF", 12.0, 2, "understand"),
        make_q("Which IS-IS metric style is required for IPv6 routing?",
               [("Narrow", False), ("Wide", True), ("Old", False), ("Legacy", False)],
               "Wide metrics are required for IS-IS multi-topology and IPv6 support.",
               "IS-IS", 12.0, 2, "remember"),

        # Extended BGP
        make_q("Which BGP attribute is used to prevent routing loops within an AS?",
               [("AS Path", True), ("Local Preference", False), ("MED", False), ("Origin", False)],
               "The AS Path attribute lists ASes a route has traversed; routers discard routes containing their own AS number.",
               "BGP", 12.0, 2, "understand"),
        make_q("Which command displays BGP routes filtered by a specific community?",
               [("show route community <community>", True), ("show bgp community", False),
                ("show route protocol bgp community", False), ("show bgp routes community", False)],
               "'show route community <community>' displays routes matching a specific BGP community.",
               "BGP", 12.0, 2, "apply"),
        make_q("Which BGP community prevents a route from being advertised outside the local AS?",
               [("no-export", True), ("no-advertise", False), ("internet", False), ("local-AS", False)],
               "The no-export community prevents a route from being advertised to eBGP peers outside the local AS.",
               "BGP", 12.0, 1, "remember"),
        make_q("Which BGP feature reduces iBGP full-mesh requirement?",
               [("Route reflector", True), ("Confederation", False), ("Add-path", False), ("Damping", False)],
               "Route reflectors allow iBGP clients to peer only with the reflector, reducing full-mesh requirements.",
               "BGP", 12.0, 2, "understand"),
        make_q("Which Junos policy action sets the BGP community?",
               [("set community <name>", True), ("set bgp-community", False),
                ("add community", False), ("write community", False)],
               "'set community <name>' adds or sets a BGP community in a Junos routing policy.",
               "BGP", 12.0, 2, "apply"),

        # Extended Multicast / CoS / EVPN
        make_q("Which PIM mode requires a rendezvous point?",
               [("PIM-SM", True), ("PIM-DM", False), ("PIM-SSM", False), ("None", False)],
               "PIM Sparse Mode requires a rendezvous point for sources and receivers to discover each other.",
               "Multicast", 8.0, 1, "remember"),
        make_q("Which CoS component classifies incoming traffic into forwarding classes?",
               [("Classifier", True), ("Rewrite rule", False), ("Scheduler", False), ("Shaper", False)],
               "Classifiers examine incoming packets and assign them to forwarding classes based on DSCP, 802.1p, etc.",
               "CoS", 8.0, 1, "remember"),
        make_q("Which EVPN route type is used for auto-discovery per ES?",
               [("Type 1", True), ("Type 2", False), ("Type 3", False), ("Type 4", False)],
               "EVPN Type 1 routes are Ethernet Auto-Discovery (A-D) routes per Ethernet Segment.",
               "EVPN", 8.0, 3, "remember"),
        make_q("Which feature prevents BUM traffic loops in EVPN multihoming?",
               [("Split horizon", True), ("STP", False), ("VRRP", False), ("LACP", False)],
               "EVPN split horizon prevents broadcast, unknown unicast, and multicast traffic from being looped back to the same ES.",
               "EVPN", 8.0, 2, "understand"),

        # Troubleshooting / CLI
        make_q("Which command shows the OSPF neighbor state on a Junos device?",
               [("show ospf neighbor", True), ("show ospf interface", False),
                ("show ospf database", False), ("show route ospf", False)],
               "'show ospf neighbor' displays OSPF neighbor adjacencies, states, and DR/BDR information.",
               "Troubleshooting", 5.0, 1, "apply"),
        make_q("Which command displays the current candidate configuration?",
               [("show", True), ("show configuration", False), ("show config", False), ("display config", False)],
               "In configuration mode, 'show' displays the candidate configuration. 'show configuration' displays the active configuration.",
               "Troubleshooting", 5.0, 1, "apply"),
        make_q("Which command compares the candidate config with the active config?",
               [("show | compare", True), ("show diff", False),
                ("compare configuration", False), ("show configuration diff", False)],
               "'show | compare' displays differences between the candidate and active configurations.",
               "Troubleshooting", 5.0, 2, "apply"),
        make_q("Which command reloads the factory-default configuration?",
               [("load factory-default", True), ("set factory-default", False),
                ("request system factory-default", False), ("reset configuration", False)],
               "'load factory-default' replaces the candidate configuration with the factory-default configuration.",
               "Troubleshooting", 5.0, 2, "apply"),
        make_q("Which command displays interface input/output errors?",
               [("show interfaces extensive", True), ("show interfaces terse", False),
                ("show interface errors", False), ("show chassis fpc", False)],
               "'show interfaces extensive' displays detailed statistics including input/output errors.",
               "Troubleshooting", 5.0, 1, "apply"),
        make_q("Which command shows active users and their login methods?",
               [("show system users", True), ("show users", False),
                ("show login users", False), ("show who", False)],
               "'show system users' displays currently logged-in users, their TTYs, and login times.",
               "Troubleshooting", 5.0, 1, "apply"),
        make_q("Which command tests Layer 3 reachability with IPv6 on modern Junos?",
               [("ping", True), ("ping6", False), ("traceroute6", False), ("telnet", False)],
               "Modern Junos supports 'ping' with both IPv4 and IPv6 destinations. Older platforms used 'ping6'.",
               "Troubleshooting", 5.0, 1, "apply"),
        make_q("Which command shows the active configuration in set format?",
               [("show configuration | display set", True), ("show | display set", False),
                ("show config set", False), ("display set", False)],
               "'show configuration | display set' outputs the active configuration as set commands.",
               "Troubleshooting", 5.0, 1, "apply"),
        make_q("Which command displays system uptime and load averages?",
               [("show system uptime", True), ("show version", False),
                ("show chassis routing-engine", False), ("show system statistics", False)],
               "'show system uptime' displays current time, uptime, and load averages.",
               "Troubleshooting", 5.0, 1, "apply"),

        # Additional Enterprise topics
        make_q("Which protocol allows a Layer 2 VLAN to span across a Layer 3 network?",
               [("VTP", False), ("VXLAN", True), ("RSTP", False), ("LACP", False)],
               "VXLAN encapsulates Layer 2 frames in UDP packets, allowing Layer 2 segments to span Layer 3 networks.",
               "Layer 2 Switching", 12.0, 2, "understand"),
        make_q("Which feature on Junos EX switches limits broadcast traffic rate?",
               [("BPDU Guard", False), ("Storm control", True), ("Root Guard", False), ("Port security", False)],
               "Storm control limits the rate of broadcast, multicast, and unknown unicast traffic on switch interfaces.",
               "Layer 2 Switching", 12.0, 2, "understand"),
        make_q("Which command shows the ARP table on a Junos router?",
               [("show arp", True), ("show route arp", False), ("show interface arp", False), ("show system arp", False)],
               "'show arp' displays the IPv4 address-to-MAC mapping table.",
               "Troubleshooting", 5.0, 1, "apply"),
        make_q("Which Junos command shows the IPv6 neighbor table?",
               [("show ipv6 neighbors", True), ("show arp", False),
                ("show route ipv6", False), ("show ipv6 route", False)],
               "'show ipv6 neighbors' displays IPv6 neighbor discovery entries, equivalent to ARP for IPv4.",
               "Troubleshooting", 5.0, 1, "apply"),
        make_q("Which OSPF cost formula is used by Junos?",
               [("reference-bandwidth / interface-bandwidth", True),
                ("10^8 / interface-bandwidth", False),
                ("interface-bandwidth / reference-bandwidth", False), ("100 / interface-bandwidth", False)],
               "Junos OSPF cost = reference-bandwidth / interface-bandwidth. The default reference bandwidth should be adjusted for high-speed links.",
               "OSPF", 12.0, 2, "understand"),
        make_q("Which IS-IS PDU is sent periodically to maintain adjacencies?",
               [("LSP", False), ("CSNP", False), ("PSNP", False), ("IIH", True)],
               "IS-IS Hello PDUs (IIH) are sent periodically to discover and maintain adjacencies.",
               "IS-IS", 12.0, 1, "remember"),
        make_q("Which command displays the IS-IS topology?",
               [("show isis topology", True), ("show isis route", False),
                ("show isis database", False), ("show isis adjacency", False)],
               "'show isis topology' displays the IS-IS shortest-path tree and topology.",
               "IS-IS", 12.0, 1, "apply"),
        make_q("Which BGP attribute is modified by the 'as-path-prepend' action?",
               [("AS Path", True), ("Origin", False), ("MED", False), ("Local Preference", False)],
               "'as-path-prepend' adds AS numbers to the AS Path attribute, making a route less preferred.",
               "BGP", 12.0, 2, "understand"),
        make_q("Which command displays routes advertised to a BGP peer?",
               [("show route advertising-protocol bgp <peer>", True),
                ("show route receive-protocol bgp <peer>", False),
                ("show bgp neighbor <peer> routes", False), ("show route protocol bgp", False)],
               "'show route advertising-protocol bgp <peer>' displays routes sent to a BGP peer.",
               "BGP", 12.0, 2, "apply"),
        make_q("Which PIM mode is best suited for one-to-many streaming with known sources?",
               [("PIM-DM", False), ("PIM-SM", False), ("PIM-SSM", True), ("Bidir-PIM", False)],
               "PIM-SSM is ideal for one-to-many streaming where receivers know the source and no RP is needed.",
               "Multicast", 8.0, 2, "understand"),
        make_q("Which EVPN route type carries MAC/IP advertisements?",
               [("Type 1", False), ("Type 2", True), ("Type 3", False), ("Type 4", False)],
               "EVPN Type 2 routes advertise MAC and IP reachability.",
               "EVPN", 8.0, 1, "remember"),
        make_q("Which CoS component drops packets based on drop probability profiles?",
               [("Scheduler", False), ("Drop profile", True), ("Rewrite rule", False), ("Classifier", False)],
               "Drop profiles define how aggressively packets are dropped based on queue fill level.",
               "CoS", 8.0, 2, "understand"),
        make_q("Which command shows the current active configuration?",
               [("show configuration", True), ("show", False),
                ("show config", False), ("display configuration", False)],
               "'show configuration' displays the active configuration in operational mode. In config mode, 'show' shows the candidate.",
               "Troubleshooting", 5.0, 1, "apply"),
        make_q("Which command saves the current active configuration as rescue configuration?",
               [("request system configuration rescue save", True),
                ("save rescue", False), ("commit rescue", False), ("load rescue", False)],
               "'request system configuration rescue save' saves the active configuration as the rescue configuration.",
               "Troubleshooting", 5.0, 2, "apply"),
        make_q("Which command displays the routing engine CPU and memory usage?",
               [("show chassis routing-engine", True), ("show system processes", False),
                ("show route summary", False), ("show system memory", False)],
               "'show chassis routing-engine' displays RE CPU, memory, and uptime.",
               "Troubleshooting", 5.0, 1, "apply"),
        make_q("Which command enables real-time monitoring of interface statistics?",
               [("monitor interface", True), ("show interfaces extensive", False),
                ("watch interface", False), ("show interface monitor", False)],
               "'monitor interface' provides real-time interface statistics, similar to top.",
               "Troubleshooting", 5.0, 2, "apply"),
        make_q("Which command captures packets on a Junos interface?",
               [("monitor traffic", True), ("capture packets", False),
                ("show traffic", False), ("trace traffic", False)],
               "'monitor traffic interface <name>' captures packets on an interface.",
               "Troubleshooting", 5.0, 2, "apply"),
        make_q("Which Junos feature applies a common configuration to multiple interfaces?",
               [("Apply-groups", True), ("Configuration templates", False), ("Macros", False), ("Variables", False)],
               "Apply-groups let you define a common configuration and apply it to multiple hierarchies.",
               "Troubleshooting", 5.0, 2, "understand"),
        make_q("Which command rolls back to the previous committed configuration?",
               [("rollback 1", True), ("rollback 0", False), ("revert 1", False), ("undo commit", False)],
               "'rollback 1' loads the previous committed configuration as the candidate. 'rollback 0' loads the current active config.",
               "Troubleshooting", 5.0, 2, "apply"),
        make_q("Which protocol resolves hostnames to IP addresses?",
               [("DHCP", False), ("DNS", True), ("NTP", False), ("SNMP", False)],
               "DNS resolves hostnames to IP addresses. DHCP assigns addresses, NTP synchronizes time, SNMP manages devices.",
               "Troubleshooting", 5.0, 1, "remember"),
        make_q("Which command displays the system hostname?",
               [("show system hostname", False), ("show configuration system host-name", True),
                ("show host-name", False), ("show system name", False)],
               "'show configuration system host-name' displays the configured hostname. 'show version' also shows it.",
               "Troubleshooting", 5.0, 1, "apply"),
        make_q("Which Junos command shows the current date and time?",
               [("show system uptime", True), ("show clock", False),
                ("show date", False), ("show time", False)],
               "'show system uptime' shows current time, uptime, and users. Junos does not use 'show clock'.",
               "Troubleshooting", 5.0, 1, "apply"),
        make_q("Which logging severity level is the most critical?",
               [("Error", False), ("Critical", False), ("Alert", False), ("Emergency", True)],
               "Syslog severity levels: Emergency (0), Alert, Critical, Error, Warning, Notice, Info, Debug (7).",
               "Troubleshooting", 5.0, 2, "remember"),
        make_q("Which command shows the configured NTP servers?",
               [("show configuration system ntp", True), ("show ntp associations", False),
                ("show system ntp", False), ("show ntp status", False)],
               "'show configuration system ntp' displays configured NTP servers. 'show ntp associations' shows active associations if ntpq is available.",
               "Troubleshooting", 5.0, 1, "apply"),
        make_q("Which feature logs every CLI command executed by users?",
               [("Syslog", False), ("Interactive-commands log", True), ("Audit log", False), ("Commit log", False)],
               "Junos logs CLI commands to the interactive-commands log file for auditing.",
               "Troubleshooting", 5.0, 2, "understand"),
        make_q("Which command displays the contents of a log file?",
               [("show log <filename>", True), ("file show <filename>", False),
                ("cat <filename>", False), ("display log <filename>", False)],
               "'show log <filename>' displays log file contents. 'file show' displays arbitrary files.",
               "Troubleshooting", 5.0, 1, "apply"),
        make_q("Which command checks file system usage on the Routing Engine?",
               [("show system storage", True), ("show chassis fpc", False),
                ("show file system", False), ("show system filesystem", False)],
               "'show system storage' displays disk usage on the RE.",
               "Troubleshooting", 5.0, 1, "apply"),
        make_q("Which command displays the current software version?",
               [("show version", True), ("show system version", False),
                ("show software", False), ("show os version", False)],
               "'show version' displays the Junos OS version, hardware model, and uptime.",
               "Troubleshooting", 5.0, 1, "apply"),

        # More enterprise and subnetting
        make_q("What is the broadcast address of 192.168.1.0/24?",
               [("192.168.1.255", True), ("192.168.1.254", False),
                ("192.168.1.0", False), ("192.168.255.255", False)],
               "For 192.168.1.0/24, the broadcast address is 192.168.1.255.",
               "Subnetting", 5.0, 1, "apply"),
        make_q("How many usable host addresses are in a /29 subnet?",
               [("6", True), ("8", False), ("4", False), ("2", False)],
               "A /29 has 8 total addresses. Subtract network and broadcast for 6 usable hosts.",
               "Subnetting", 5.0, 2, "apply"),
        make_q("Which subnet mask corresponds to a /26 prefix?",
               [("255.255.255.192", True), ("255.255.255.224", False),
                ("255.255.255.128", False), ("255.255.255.240", False)],
               "/26 = 255.255.255.192, providing 64 addresses per subnet.",
               "Subnetting", 5.0, 1, "apply"),
        make_q("What is the first valid host in 10.0.0.0/30?",
               [("10.0.0.0", False), ("10.0.0.1", True), ("10.0.0.2", False), ("10.0.0.3", False)],
               "10.0.0.0/30 has network 10.0.0.0 and broadcast 10.0.0.3. First host is 10.0.0.1.",
               "Subnetting", 5.0, 2, "apply"),
        make_q("Which VRRP state actively forwards traffic for the virtual IP?",
               [("Initialize", False), ("Backup", False), ("Master", True), ("Active", False)],
               "In VRRP, the Master router forwards traffic for the virtual IP. Backup routers take over if Master fails.",
               "Layer 2 Switching", 12.0, 2, "understand"),
        make_q("Which command shows the aggregated Ethernet interface status on Junos?",
               [("show interfaces ae0 extensive", True), ("show ae0", False),
                ("show interface aggregate", False), ("show ethernet-switching ae0", False)],
               "'show interfaces ae0 extensive' displays detailed status of aggregated Ethernet interfaces.",
               "Troubleshooting", 5.0, 1, "apply"),
        make_q("Which feature prevents a switch port from learning too many MAC addresses?",
               [("BPDU Guard", False), ("Port security", True), ("Root Guard", False), ("Storm control", False)],
               "Port security limits the number of MAC addresses on a port, preventing MAC flooding.",
               "Layer 2 Switching", 12.0, 2, "understand"),
        make_q("Which Junos command shows OSPF interface state?",
               [("show ospf interface", True), ("show ospf neighbor", False),
                ("show ospf database", False), ("show interface ospf", False)],
               "'show ospf interface' displays OSPF-enabled interfaces, area, state, and DR/BDR info.",
               "Troubleshooting", 5.0, 1, "apply"),
        make_q("Which command verifies IS-IS adjacency state?",
               [("show isis adjacency", True), ("show isis neighbor", False),
                ("show isis interface", False), ("show isis database", False)],
               "'show isis adjacency' displays IS-IS neighbors and their states.",
               "Troubleshooting", 5.0, 1, "apply"),
        make_q("Which command shows the BGP routing information base?",
               [("show bgp summary", False), ("show route protocol bgp", True),
                ("show bgp database", False), ("show route table bgp", False)],
               "'show route protocol bgp' displays routes learned via BGP in the routing table.",
               "Troubleshooting", 5.0, 2, "apply"),
        make_q("Which protocol is used for link-state routing in large enterprise networks?",
               [("RIP", False), ("OSPF", True), ("BGP", False), ("Static routing", False)],
               "OSPF is a link-state IGP commonly used in large enterprise networks.",
               "OSPF", 12.0, 1, "remember"),
        make_q("Which command displays the forwarding table on Junos?",
               [("show route forwarding-table", True), ("show forwarding-table", False),
                ("show route table", False), ("show fpc forwarding", False)],
               "'show route forwarding-table' displays the forwarding table used by the PFE.",
               "Troubleshooting", 5.0, 1, "apply"),
        make_q("Which Junos configuration mode command shows only the changes made in the current session?",
               [("show | compare", True), ("show diff", False),
                ("show changes", False), ("show configuration | display set", False)],
               "'show | compare' in configuration mode shows the diff between candidate and active configurations.",
               "Troubleshooting", 5.0, 2, "apply"),
        make_q("Which command loads a previously saved rescue configuration?",
               [("load rescue", True), ("rollback rescue", False),
                ("commit rescue", False), ("request rescue", False)],
               "'load rescue' loads the saved rescue configuration into the candidate config.",
               "Troubleshooting", 5.0, 2, "apply"),
        make_q("Which feature allows a Junos device to archive configurations automatically?",
               [("Configuration archival", True), ("Rescue config", False),
                ("Commit scripts", False), ("Rollback", False)],
               "Configuration archival automatically saves configurations to remote servers at defined intervals.",
               "Troubleshooting", 5.0, 2, "understand"),
        make_q("Which command checks the status of the Routing Engine?",
               [("show chassis routing-engine", True), ("show system processes", False),
                ("show route summary", False), ("show chassis fpc", False)],
               "'show chassis routing-engine' displays RE status, CPU, memory, and uptime.",
               "Troubleshooting", 5.0, 1, "apply"),
        make_q("Which command displays active alarms?",
               [("show system alarms", True), ("show chassis alarms", False),
                ("show alarms", False), ("show log alarms", False)],
               "'show system alarms' displays active red and yellow alarms.",
               "Troubleshooting", 5.0, 1, "apply"),
    ]

    # Deduplicate
    seen = set()
    unique = []
    for q in questions:
        if q["body"] not in seen:
            seen.add(q["body"])
            unique.append(q)
    return unique


def questions_to_sql(questions: list[dict]) -> str:
    lines = [
        "-- +goose Up",
        "-- +goose StatementBegin",
        "",
        "-- JNCIP-ENT (JN0-649) question bank",
        f"-- Generated {len(questions)} blueprint-aligned single-choice questions",
        "",
        "DELETE FROM questions WHERE exam_id = 'b0000000-0000-0000-0000-000000000011';",
        "",
    ]
    for q in questions:
        options_json = json.dumps(q["options"], ensure_ascii=False)
        urls = "{" + ",".join(f'"{u}"' for u in q["reference_urls"]) + "}"
        lines.append(
            f"INSERT INTO questions (id, exam_id, track_id, question_type, difficulty, bloom_level, body, options, explanation, reference_urls, blueprint_section, blueprint_weight, content_hash, is_active) VALUES ("
            f"'{q['id']}', "
            f"'{q['exam_id']}', "
            f"'{q['track_id']}', "
            f"'{q['question_type']}', "
            f"{q['difficulty']}, "
            f"'{q['bloom_level']}', "
            f"$${q['body']}$$::text, "
            f"$${options_json}$$::jsonb, "
            f"$${q['explanation']}$$::text, "
            f"$${urls}$$::text[], "
            f"$${q['blueprint_section']}$$::text, "
            f"{q['blueprint_weight']}, "
            f"'{q['content_hash']}', "
            f"{str(q['is_active']).lower()}"
            f") ON CONFLICT (id) DO NOTHING;"
        )
    lines += [
        "",
        "-- +goose StatementEnd",
        "",
        "-- +goose Down",
        "-- +goose StatementBegin",
        "",
        "DELETE FROM questions WHERE exam_id = 'b0000000-0000-0000-0000-000000000011';",
        "",
        "-- +goose StatementEnd",
    ]
    return "\n".join(lines)


if __name__ == "__main__":
    questions = generate_questions()
    print(questions_to_sql(questions))
